### PR TITLE
Add .dat-to-.csv converter and add converted CSV files for (nearly) all .dta files

### PR DESCRIPTION
**Pull request by jsvine**
Cf. https://github.com/worldbank/SDI-Health/issues/1

The conversions were performed using the `scripts/format-conversion/dta-to-csv.py` script, which is written in Python, and depends only on Python 3 and [`pandas`](https://pandas.pydata.org/). Usage examples are noted at the top of that script.

The script successfully converts 100 of the 101 .dat files in this repository, but fails on `rawData/SDI_Tanzania-2016/SDI_Tanzania-2016_Module3_Raw.dta`. For that file, the script throws the following exception: 

`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe6 in position 16: invalid continuation byte`  (in the context of `pandas/io/stata.py, line 1179, in _get_variable_labels`)

... which suggests to me that there may be an unexpected character, or unconventional encoding, in that file's variable labels, but I don't know for sure.

### CODE REVIEW

**Comment by wanghaisheng** [comment]
love that

**Comment by bbdaniels** [comment]
Removed what I believe to be the offending character in 5d41dc794f9fd420e0841f468fc1a49936d0e5d3 and sent back to yours as jsvine/SDI-Health/pull/1 so I can approve just one PR here with the final CSV file after another commit there.

However I am not getting the script to work on the new file myself, what am I doing wrong here?

```
Benjamins-iMac:SDI-Health bbdaniels$ python  scripts/format-conversion/dta-to-csv.py rawData/SDI_Tanzania-2016/SDI_Tanzania-2016_Module3_Raw.dta
  File "scripts/format-conversion/dta-to-csv.py", line 25
    sys.stderr.write(f"Converting {path}")
```

**Comment by jsvine** [comment]
Thanks! Merged that fix, and converted the fixed file. Now added to this PR.

Re. not getting the script to work: My best guess is that your `python` command is linked to Python 2. You can test this by running `python --version`. If it's indeed Python 2, and if you also have Python 3 installed, then `python3  scripts/format-conversion/dta-to-csv.py [...]` should work.

(To check whether you have Python 3 installed, try running `which python3`. If that prints a path, then you have Python 3. If it returns nothing, then you can download Python 3 from https://www.python.org/downloads/, or via `brew install python` [on MacOS], or however you prefer to install software.)

**Comment by bbdaniels** [comment]
That makes sense, I will check my Python version. Thanks! Merging and closing.

**Pull request merged**
